require("esbuild").buildSync({
  entryPoints: [
    "./src/app.js",
    "./src/sw.js",
    "./src/index.css",
    "./src/components/baseComp.js",
    "./src/components/button.js",
    "./src/components/noteListComp.js",
    "./src/dataStore/dataStore.js",
    "./src/templates/mainContentBox.js",
    "./src/templates/newButton.js",
    "./src/templates/saveButton.js",
    "./src/templates/titleBox.js",
    "./src/templates/notesList.js",
  ],
  bundle: true,
  minify: true,
  sourcemap: true,
  target: ["chrome89", "firefox89", "safari15", "edge89"],
  outdir: "./dist",
});
